apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - n3xtcut.com
        - www.n3xtcut.com
      secretName: n3xtcut-com
  rules:
    - host: n3xtcut.com
      http:
        paths:
          - path: /api/(.+)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
          - path: /(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
    - host: www.n3xtcut.com
      http:
        paths:
          - path: /api/(.+)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
          - path: /(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000

    
          
