apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #certificate setup
    #certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    #nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  #https config
  #tls:
    #- hosts:
        #- domain.com
        #- www.domain.com
        #secretName: secretName from certificate yaml
  rules:
    #https config
    #- host: domain.com
    - http:
        paths:
          - path: /api/(.+)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
          - path: /(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000

    #https config
    #- host: www.domain.com
    # - http:
    #     paths:
    #       - path: /api/(.+)
    #         backend:
    #           serviceName: server-cluster-ip-service
    #           servicePort: 5000
    #       - path: /(.*)
    #         backend:
    #           serviceName: client-cluster-ip-service
    #           servicePort: 3000
          
